# Use the official Ubuntu base image
FROM ubuntu:latest

# Update package lists and install dependencies
RUN apt-get update && apt-get install -y \
    python3.10 \
    python3-pip \
    git

# Install the PyYAML Python package
RUN pip3 install PyYAML

# Copy the feed.py script to the /usr/bin/ directory
COPY feed.py /usr/bin/feed.py

# Copy the entrypoint.sh script to the root directory
COPY entrypoint.sh /entrypoint.sh



# Set the entrypoint to the entrypoint.sh script
ENTRYPOINT ["/entrypoint.sh"]
